### ISSUE TITLE
Source links should open in new tab.

### ISSUE THREAD

**Issue by ChucklezPC2** [jbolduan/didtrumpdoit#1]
Source links that are in square brackets ( [1], [2], etc.) should open in a new tab instead of the current one.   This is so that when someone clicks on them, they are not completely taken away from the site.

**Comment by jbolduan** [comment]
I fixed this bug, thank you for reporting it!  I had forgotten this was how it was working but it should now open up external links and also not trigger the row link to each statements individual page.
